import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';

import { Toaster } from 'sonner';

import { Navbar } from '~/components';
import { customFetchServer } from '~/http';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await customFetchServer<{
    currentUser: { id: string; email: string } | null;
  }>('http://auth-srv:3000/api/users/current-user', headers).catch(() => ({ data: null }));

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={response.data?.currentUser ?? null} />
        <main className="mx-auto max-w-[1200px] px-6 py-8">{children}</main>
        <Toaster visibleToasts={5} pauseWhenPageIsHidden />
      </body>
    </html>
  );
}
