apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: berkinanik/ticketing-client:latest
          env:
            - name: STRIPE_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-client-secret
                  key: STRIPE_CLIENT_KEY
          livenessProbe:
            httpGet:
              path: /health/check
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
