name: Tests

on:
  pull_request:
    paths-ignore:
      - 'infra/**'

concurrency:
  group: dev-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  cache-and-install:
    name: Cache and Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test:ci
